language: r
cache: packages

matrix:
  include:
   - os: linux
     r: release
   - os: linux
     r: devel
   - os: osx
     r: release
   - os: osx
     r: devel

before_install:
  - R -e 'install.packages("devtools")'
  
install:
  - R -e 'install.packages("shiny")'
  - R -e 'install.packages("shinythemes")'
  - R -e 'devtools::install_github("jrowen/rhandsontable")'

warnings_are_errors: false

env:
  global:
   - CRAN: http://cran.rstudio.com